#!/usr/bin/env bash

up() {
  echo "Starting Portainer Agent..."
  docker pull portainer/agent:2.18.4
  docker run -d \
  -p 9001:9001 \
  --name portainer_agent \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/lib/docker/volumes:/var/lib/docker/volumes \
  portainer/agent:2.18.4

  echo "Starting Krakend..."
  docker pull devopsfaith/krakend
  docker run -d -p 8080:8080 \
  -v $PWD:/etc/krakend/ \
  --name creasc-gateway-api devopsfaith/krakend

  echo "See sample results on: http://localhost:8080/test"
}

down() {
  echo "Stopping Gateway-api..."
  docker stop creasc-gateway-api
  docker rm creasc-gateway-api

  echo "Stopping Portainer Agent..."
  docker stop portainer_agent
  docker rm portainer_agent
}

case $1 in
  up)
    up
    ;;
  down)
    down
    ;;
  *)
    echo "Usage: $0 {up|down}"
    ;;
esac
  
